--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Julicraft44/VanillaXP
build-by-default: true
branches:
- main
projects:
  VanillaXP:
    path: ""
    lint:
      phpstan: false
    icon:
      icon.png
...
